---
docker:
  # GitLab Docker Registry
  registry: registry.gitlab.com/ownport/docker-images

kaniko:
  config: /kaniko/.docker/config.json

gitlab:
  stages:
  - buildtools
  - base 

  # python
  - python
  - python-dev
  - python-dev-vscode

  - openjdk
  - sbt
  - scala

  - nodejs
  - rust
  - bigdata
  - data-science
  - workflows
  - scraping

  # tools
  - bazel
  - bazel-dind
  - kaniko
  - kaniko-builder
