---
docker:
  # GitLab Docker Registry
  registry: registry.gitlab.com/ownport/docker-images

gitlab:
  stages:
  - buildtools
  - base 
  - python
  - python-dev
  - python-dev-vscode
  - openjdk
  - sbt
  - scala
  - nodejs
  - rust
  - bigdata
  - data-science
  - workflows
  - scraping
  - bazel
  - kaniko

