default:
  image: docker:stable

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  
services:
- docker:stable-dind

# include:
#   - template: Container-Scanning.gitlab-ci.yml

stages:
- prepare
- changed targets
- base

before_script:
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
- apk add python3 git

targets list:
  stage: prepare
  script:
  - python3 -m buildtools git --branch origin/$CI_COMMIT_REF_NAME --tag $CI_COMMIT_TAG --fetch-target-branch
  - python3 -m buildtools git --branch origin/$CI_COMMIT_REF_NAME --tag $CI_COMMIT_TAG --show-changed-files
  - python3 -m buildtools target --branch origin/$CI_COMMIT_REF_NAME --tag $CI_COMMIT_TAG --generate-pipeline > changed-targets.yaml
  - cat changed-targets.yaml
  artifacts:
    paths:
    - changed-targets.yaml

trigger targets builds:
  stage: changed targets
  needs:
  - targets list
  trigger:
    include:
    - artifact: changed-targets.yaml
      job: targets list
    strategy: depend
    

