default:
  image: docker:stable

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  
services:
- docker:stable-dind

# include:
#   - template: Container-Scanning.gitlab-ci.yml

stages:
- prepare
- changed targets
- base

before_script:
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
- apk add python3 git

targets list:
  stage: prepare
  script:
  - echo CI_COMMIT_BRANCH $CI_COMMIT_BRANCH
  - echo CI_COMMIT_REF_NAME $CI_COMMIT_REF_NAME
  - echo CI_COMMIT_REF_SLUG $CI_COMMIT_REF_SLUG
  - echo CI_COMMIT_TAG $CI_COMMIT_TAG
  - echo CI_DEFAULT_BRANCH $CI_DEFAULT_BRANCH
  - echo CI_PIPELINE_SOURCE $CI_PIPELINE_SOURCE
  - python3 -m buildtools git --set-branch-name origin/$CI_COMMIT_REF_NAME --fetch-target-branch
  - python3 -m buildtools target --branch-name origin/$CI_COMMIT_REF_NAME --generate-pipeline > changed-targets.yaml
  - cat changed-targets.yaml
  artifacts:
    paths:
    - changed-targets.yaml

trigger targets builds:
  stage: changed targets
  needs:
  - targets list
  trigger:
    include:
    - artifact: changed-targets.yaml
      job: targets list
    strategy: depend
    

