default:
  # image: docker:stable
  image: registry.gitlab.com/ownport/docker-images/bazel:4.2-dind-ubuntu

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  
before_script:
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    bazel --output_base output build //...
  artifacts:
    paths:
      - bazel-bin/
  cache:
    key: cc195b00504e0a277a45468edc8a9673d
    paths:
      - output        

