default:
<<<<<<< HEAD
  # image: docker:stable
  # image: registry.gitlab.com/ownport/docker-images/release/kaniko-builder:1.6-ubuntu
  image: registry.gitlab.com/ownport/docker-images/release/python-dev:3.9-alpine

# variables:
#   DOCKER_TLS_CERTDIR: "/certs"
  
# services:
# - docker:stable-dind

# include:
#   - template: Container-Scanning.gitlab-ci.yml
=======
  image: registry.gitlab.com/ownport/docker-images/release/python-dev:3.9-alpine
>>>>>>> origin-devel

stages:
- prepare
- changed targets
<<<<<<< HEAD

# before_script:
# - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
# - apk add python3 git
=======
>>>>>>> origin-devel

targets list:
  stage: prepare
  script:
  - ./builder git --branch origin/$CI_COMMIT_REF_NAME --tag $CI_COMMIT_TAG --fetch-target-branch
  - ./builder git --branch origin/$CI_COMMIT_REF_NAME --tag $CI_COMMIT_TAG --show-changed-files
  - ./builder target --branch origin/$CI_COMMIT_REF_NAME --tag $CI_COMMIT_TAG --generate-pipeline > changed-targets.yaml
  - cat changed-targets.yaml
  artifacts:
    paths:
    - changed-targets.yaml

trigger targets builds:
  stage: changed targets
  needs:
  - targets list
  trigger:
    include:
    - artifact: changed-targets.yaml
      job: targets list
    strategy: depend
    

