default:
  image: docker:stable

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  
services:
  - docker:stable-dind

# include:
#   - template: Container-Scanning.gitlab-ci.yml
  
before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - apk add bash

stages:
  - base
  - base:python
  - dev:python
  - dev:vscode
  - tools

# ==================================================================
# Base images: Alpine
#
base:alpine-3.12:
  stage: base
  script:
    - ./manage.sh build images/base/alpine-3.12
    - ./manage.sh test images/base/alpine-3.12
    - ./manage.sh publish-to-gitlab-registry images/base/alpine-3.12
  # only:
  # - tags

base:alpine-3.13:
  stage: base
  script:
    - ./manage.sh build images/base/alpine-3.13
    - ./manage.sh test images/base/alpine-3.13
    - ./manage.sh publish-to-gitlab-registry images/base/alpine-3.13
  # only:
  # - tags

# ==================================================================
# Base images: Ubuntu
#
base:ubuntu-20.04:
  stage: base
  script:
    - ./manage.sh build images/base/ubuntu-20.04
    - ./manage.sh test images/base/ubuntu-20.04
    - ./manage.sh publish-to-gitlab-registry images/base/ubuntu-20.04
  # only:
  # - tags

base:ubuntu-20.10:
  stage: base
  script:
    - ./manage.sh build images/base/ubuntu-20.10
    - ./manage.sh test images/base/ubuntu-20.10
    - ./manage.sh publish-to-gitlab-registry images/base/ubuntu-20.10
  # only:
  # - tags

# ==================================================================
# Python 3.8 Alpine
#
python:3.8-alpine:
  stage: base:python
  script:
    - ./manage.sh build images/python/3.8-alpine
    - ./manage.sh test images/python/3.8-alpine
    - ./manage.sh publish-to-gitlab-registry images/python/3.8-alpine
  dependencies:
    - base:alpine-3.13
  # only:
  # - tags

python:3.8-dev-alpine:
  stage: dev:python
  script:
    - ./manage.sh build images/python/3.8-dev-alpine
    - ./manage.sh test images/python/3.8-dev-alpine
    - ./manage.sh publish-to-gitlab-registry images/python/3.8-dev-alpine
  dependencies:
    - python:3.8-alpine
  # only:
  # - tags

python:3.8-dev-vscode-alpine:
  stage: dev:vscode
  script:
    - ./manage.sh build images/python/3.8-dev-vscode-alpine
    - ./manage.sh test images/python/3.8-dev-vscode-alpine
    - ./manage.sh publish-to-gitlab-registry images/python/3.8-dev-vscode-alpine
  dependencies:
    - python:3.8-dev-alpine
  # only:
  # - tags

# ==================================================================
# Utils
#
# transmission:3.0-alpine:
#   stage: tools
#   script:
#     - ./manage.sh build images/tools/transmission/3.0-alpine
#     - ./manage.sh test images/tools/transmission/3.0-alpine
#     - ./manage.sh publish-to-gitlab-registry images/tools/transmission/3.0-alpine
#   dependencies:
#     - base:alpine-3.13

tracker:3.0-alpine:
  stage: tools
  script:
    - ./manage.sh build images/tools/tracker/3.0-alpine
    - ./manage.sh test images/tools/tracker/3.0-alpine
    - ./manage.sh publish-to-gitlab-registry images/tools/tracker/3.0-alpine
  dependencies:
    - base:alpine-3.13
